---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: 1.15.3
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: cilium
  storageNamespace: kube-system
  targetNamespace: kube-system
  values:
    operator:
      replicas: 1
