apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    release: grafana
spec:
  config:
    analytics:
      check_for_plugin_updates: "false"
      check_for_updates: "false"
      enable_feedback_links: "false"
      reporting_enabled: "false"
    auth.anonymous:
      enabled: "true"
      org_role: Viewer
      hide_version: "true"
    plugins:
      preinstall_sync: "victoriametrics-logs-datasource"
