---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  chart:
    spec:
      chart: grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 6.36.2
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: grafana
  storageNamespace: grafana
  targetNamespace: grafana
  values:
    adminPassword: prom-operator
    grafana.ini:
      analytics:
        check_for_updates: false
      auth.anonymous:
        enabled: true
        org_role: Viewer
        hide_version: true
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
