groups:
  - name: general
    rules:
      - alert: Watchdog
        annotations:
          description: |
            This is an alert meant to ensure that the entire alerting pipeline is functional.
            This alert is always firing, therefore it should always be firing in Alertmanager
            and always fire against a receiver. There are integrations with various notification
            mechanisms that send a notification when this alert is not firing. For example the
            "DeadMansSnitch" integration in PagerDuty.
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/general/watchdog
          summary: An alert that should always be firing to certify that Alertmanager
            is working properly.
        expr: 1
        labels:
          severity: none
      - alert: Testing
        annotations:
          description: |
            User {{ $labels.user }} needed more than 10 seconds to perform
            operation.
          summary: User {{ $labels.user }} gets annoyed.
        expr: 'count_over_time({app="debug"} |= "Operation" | regexp `needed (?P<time>[0-9]+) seconds for user (?P<user>[0-9]+)` | time >= 10 [1m]) > 0'
        labels:
          severity: info
