---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      version: 3.8.3
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: metrics-server
  storageNamespace: kube-system
  targetNamespace: kube-system
