---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  chart:
    spec:
      chart: promtail
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 6.3.0
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: promtail
  storageNamespace: promtail
  targetNamespace: promtail

