---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  chart:
    spec:
      chart: promtail
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 6.3.0
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: promtail
  storageNamespace: promtail
  targetNamespace: promtail
  values:
    config:
      clients:
        - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
