---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  chart:
    spec:
      chart: promtail
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 6.17.0
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: promtail
  storageNamespace: promtail
  targetNamespace: promtail
  values:
    config:
      clients:
        - url: http://victorialogs-victoria-logs-single-server.victorialogs.svc.cluster.local:9428/insert/loki/api/v1/push
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      metricRelabelings:
        - action: drop
          regex: promtail_(file_bytes_total|read_bytes_total|read_lines_total)
          sourceLabels:
            - __name__
