apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
configMapGenerator:
  - name: consoles
    namespace: prometheus
    options:
      disableNameSuffixHash: true
    files:
      - consoles/index.html.example
      - consoles/node-cpu.html
      - consoles/node-disk.html
      - consoles/node-overview.html
      - consoles/node.html
      - consoles/prometheus-overview.html
      - consoles/prometheus.html
