apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
# FIXME: This `configMapGenerator` can ends up in failing if `prometheus`
# FIXME: namespace does not exists yet and it will need a manual
# FIXME: `kubectl create namespace prometheus`. Unfortunately we could not
# FIXME: create dependencies or similar because the configMap is directly
# FIXME: consumed by the HelmRelease. To avoid that we should directly add an
# FIXME: explicit Namespace resource picked up by the Kustomization.
configMapGenerator:
  - name: consoles
    namespace: prometheus
    options:
      disableNameSuffixHash: true
    files:
      - consoles/index.html.example
      - consoles/node-cpu.html
      - consoles/node-disk.html
      - consoles/node-overview.html
      - consoles/node.html
      - consoles/prometheus-overview.html
      - consoles/prometheus.html
