apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victorialogs
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      release: grafana
  datasource:
    name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: |-
      http://victorialogs-victoria-logs-single-server.victorialogs.svc.cluster.local:9428
