---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victorialogs
  namespace: flux-system
spec:
  values:
    server:
      persistentVolume:
        size: 5Gi
      retentionDiskSpaceUsage: 5GB
      retentionPeriod: 7d
      serviceMonitor:
        enabled: true
        extraLabels:
          release: kube-prometheus-stack
  chart:
    spec:
      chart: victoria-logs-single
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
      version: 0.11.6
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: victorialogs
  storageNamespace: victorialogs
  targetNamespace: victorialogs
