apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: readeck
  namespace: readeck
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: readeck
  body:
    maxSize: "20m"
