apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
configMapGenerator:
  - name: rules
    namespace: loki
    files:
      - rules/general.yaml
generatorOptions:
  disableNameSuffixHash: true
