---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 3.0.1
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: loki
  storageNamespace: loki
  targetNamespace: loki
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
    monitoring:
      alerts:
        labels:
          release: kube-prometheus-stack
      rules:
        labels:
          release: kube-prometheus-stack
      serviceMonitor:
        labels:
          release: kube-prometheus-stack
    singleBinary:
      persistence:
        size: 1Gi
