---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 3.0.1
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: loki
  storageNamespace: loki
  targetNamespace: loki
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      structuredConfig:
        ruler:
          alertmanager_url: http://kube-prometheus-stack-alertmanager.prometheus.svc.cluster.local:9093
          external_labels:
            loki: "loki/loki"
    monitoring:
      alerts:
        labels:
          release: kube-prometheus-stack
      rules:
        labels:
          release: kube-prometheus-stack
      serviceMonitor:
        labels:
          release: kube-prometheus-stack
    singleBinary:
      extraVolumeMounts:
        - name: rules
          mountPath: /var/loki/rules/fake
      extraVolumes:
        - name: rules
          configMap:
            name: rules
            defaultMode: 0444
      persistence:
        size: 1Gi
