---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: kgateway
    namespace: flux-system
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: kgateway
  storageNamespace: kgateway-system
  targetNamespace: kgateway-system
  values:
    image:
      # XXX: On Flux the KGW_DEFAULT_IMAGE_TAG ends up as 2.1.2+86e6dc75ea16
      # XXX: instead of just 2.1.2. Hardcode that.
      # XXX: Please see <https://github.com/kgateway-dev/kgateway/issues/13222>
      tag: "v2.1.2"
