---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  values:
    controller:
      metrics:
        enabled: true
        prometheusRule:
          enabled: true
          namespace: prometheus
          additionalLabels:
            release: kube-prometheus-stack
          rules:
            - alert: NGINXDown
              annotations:
                description: >
                  NGINX Ingress Controller disappeared from Prometheus target
                  discovery.
                summary: >
                  NGINX Ingress Controller disappeared from Prometheus target
                  discovery.
              expr: absent(up{job="ingress-nginx-controller-metrics"})
              for: 15m
              labels:
                severity: critical
            - alert: NGINXConfigFailed
              annotations:
                description: >
                  NGINX Ingress Controller configuration could not be loaded.
                summary: NGINX Ingress Controller configuration is invalid.
              expr: count(nginx_ingress_controller_config_last_reload_successful == 0) > 0
              for: 1m
              labels:
                severity: warning
            - alert: NGINXCertificateExpiry
              annotations:
                description: >
                  SSL certificate(s) will expire in less then a week.
                summary: Expiring SSL certificate(s).
              expr: (avg(nginx_ingress_controller_ssl_expire_time_seconds{host!="_"}) by (host) - time()) < 604800
              for: 1m
              labels:
                severity: warning
        serviceMonitor:
          enabled: true
          namespace: prometheus
          additionalLabels:
            release: kube-prometheus-stack
          namespaceSelector:
            matchNames:
              - ingress-nginx
      service:
        externalTrafficPolicy: Local
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.12.3
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: ingress-nginx
  storageNamespace: ingress-nginx
  targetNamespace: ingress-nginx
